import { ComponentFixture, TestBed } from '@angular/core/testing';
import { provideZonelessChangeDetection } from '@angular/core';
import { provideHttpClient } from '@angular/common/http';
import { provideHttpClientTesting, HttpTestingController } from '@angular/common/http/testing';
import { CellEditor } from './cell-editor';
import { ExcelService } from '../../core/services/excel.service';
import { ToastService } from '../../core/services/toast.service';
import {
  SdrfSyntaxService,
  OntologySearchService,
  MetadataColumn,
  OntologyType,
  OntologySuggestion
} from '@noatgnu/cupcake-vanilla';
import { CUPCAKE_CORE_CONFIG } from '@noatgnu/cupcake-core';

function createMockColumn(overrides: Partial<MetadataColumn> = {}): MetadataColumn {
  return {
    id: 1,
    metadataTable: 1,
    name: 'test column',
    type: 'characteristics',
    columnPosition: 0,
    value: '',
    notApplicable: false,
    notAvailable: false,
    mandatory: false,
    hidden: false,
    autoGenerated: false,
    readonly: false,
    modifiers: [],
    suggestedValues: [],
    enableTypeahead: true,
    possibleDefaultValues: [],
    staffOnly: false,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    ...overrides
  };
}

describe('CellEditor', () => {
  let component: CellEditor;
  let fixture: ComponentFixture<CellEditor>;
  let httpMock: HttpTestingController;
  let excelServiceSpy: jasmine.SpyObj<ExcelService>;
  let toastServiceSpy: jasmine.SpyObj<ToastService>;

  const mockColumn = createMockColumn({
    name: 'characteristics[organism]',
    ontologyType: OntologyType.SPECIES
  });

  const mockAgeColumn = createMockColumn({
    id: 2,
    name: 'characteristics[age]',
    columnPosition: 1
  });

  const mockModificationColumn = createMockColumn({
    id: 3,
    name: 'comment[modification parameters]',
    type: 'comment',
    columnPosition: 2,
    ontologyType: OntologyType.UNIMOD
  });

  beforeEach(async () => {
    jasmine.clock().install();

    excelServiceSpy = jasmine.createSpyObj('ExcelService', ['getSelectedRange', 'updateCell']);
    toastServiceSpy = jasmine.createSpyObj('ToastService', ['success', 'error', 'warning', 'info']);

    excelServiceSpy.getSelectedRange.and.returnValue(Promise.resolve({
      address: 'Sheet1!A2',
      values: [['test value']]
    }));
    excelServiceSpy.updateCell.and.returnValue(Promise.resolve());

    await TestBed.configureTestingModule({
      imports: [CellEditor],
      providers: [
        provideZonelessChangeDetection(),
        provideHttpClient(),
        provideHttpClientTesting(),
        SdrfSyntaxService,
        OntologySearchService,
        { provide: CUPCAKE_CORE_CONFIG, useValue: { apiUrl: 'http://localhost:8000/api/v1' } },
        { provide: ExcelService, useValue: excelServiceSpy },
        { provide: ToastService, useValue: toastServiceSpy }
      ]
    }).compileComponents();

    httpMock = TestBed.inject(HttpTestingController);
  });

  afterEach(() => {
    jasmine.clock().uninstall();
    httpMock.verify();
  });

  function createComponent(column: MetadataColumn, currentValue: string = ''): void {
    fixture = TestBed.createComponent(CellEditor);
    component = fixture.componentInstance;
    fixture.componentRef.setInput('column', column);
    fixture.componentRef.setInput('currentValue', currentValue);
    fixture.detectChanges();
  }

  it('should create', () => {
    createComponent(mockColumn);
    expect(component).toBeTruthy();
  });

  it('should detect ontology column', () => {
    createComponent(mockColumn);
    expect(component.hasOntology()).toBeTrue();
  });

  it('should detect age syntax type', () => {
    createComponent(mockAgeColumn);
    expect(component.syntaxType()).toBe('age');
  });

  it('should detect modification syntax type', () => {
    createComponent(mockModificationColumn);
    expect(component.syntaxType()).toBe('modification');
  });

  it('should initialize with current value', () => {
    createComponent(mockColumn, 'Homo sapiens');
    expect(component.editValue()).toBe('Homo sapiens');
  });

  it('should show ontology label for ontology column', () => {
    createComponent(mockColumn);
    expect(component.ontologyLabel()).toBeTruthy();
  });

  it('should trigger ontology search on input', () => {
    createComponent(mockColumn);

    component.onValueInput('human');
    jasmine.clock().tick(351);

    const req = httpMock.expectOne(req => req.url.includes('/ontology/search/suggest/'));
    expect(req.request.params.get('q')).toBe('human');
    expect(req.request.params.get('type')).toBe('species');
    req.flush({ suggestions: [] });
  });

  it('should select ontology suggestion with displayName only', async () => {
    createComponent(mockColumn);

    const suggestion: OntologySuggestion = {
      id: '9606',
      value: 'Homo sapiens',
      displayName: 'Homo sapiens',
      ontologyType: OntologyType.SPECIES
    };

    component.selectSuggestion(suggestion);
    await fixture.whenStable();

    expect(component.editValue()).toBe('Homo sapiens');
    expect(component.showSuggestions()).toBeFalse();
  });

  it('should format MS_UNIQUE_VOCABULARIES with NT/AC syntax', async () => {
    createComponent(mockColumn);

    const suggestion: OntologySuggestion = {
      id: 'MS:1001251',
      value: 'Trypsin',
      displayName: 'Trypsin',
      ontologyType: OntologyType.MS_UNIQUE_VOCABULARIES,
      fullData: {
        name: 'Trypsin',
        accession: 'MS:1001251'
      }
    };

    component.selectSuggestion(suggestion);
    await fixture.whenStable();

    expect(component.editValue()).toBe('NT=Trypsin;AC=MS:1001251');
  });

  it('should hide suggestions after delay', () => {
    createComponent(mockColumn);
    component.showSuggestions.set(true);

    component.hideSuggestions();
    expect(component.showSuggestions()).toBeTrue();

    jasmine.clock().tick(251);
    expect(component.showSuggestions()).toBeFalse();
  });

  it('should insert value to cell', async () => {
    createComponent(mockColumn, 'Homo sapiens');

    component.insertToCell();
    await fixture.whenStable();

    expect(excelServiceSpy.updateCell).toHaveBeenCalled();
    expect(toastServiceSpy.success).toHaveBeenCalledWith('Inserted into cell');
  });

  it('should emit close on cancel', () => {
    createComponent(mockColumn);
    const closeSpy = spyOn(component.close, 'emit');

    component.cancel();

    expect(closeSpy).toHaveBeenCalled();
  });

  it('should emit saved value on save', async () => {
    createComponent(mockColumn, 'Homo sapiens');
    const savedSpy = spyOn(component.saved, 'emit');

    component.save();
    await fixture.whenStable();

    expect(savedSpy).toHaveBeenCalledWith('Homo sapiens');
    expect(toastServiceSpy.success).toHaveBeenCalledWith('Value saved');
  });

  it('should handle special value change from sub-component', () => {
    createComponent(mockAgeColumn);

    component.onSpecialValueChange('30Y6M');

    expect(component.editValue()).toBe('30Y6M');
  });

  it('should get ontology type label', () => {
    createComponent(mockColumn);

    const label = component.getOntologyTypeLabel('species');
    expect(label).toBe('Species');
  });

  it('should handle insert error gracefully', async () => {
    createComponent(mockColumn);
    excelServiceSpy.getSelectedRange.and.returnValue(Promise.reject('Excel error'));

    component.insertToCell();
    await fixture.whenStable();

    expect(toastServiceSpy.error).toHaveBeenCalledWith('Failed to insert into cell');
  });

  it('should not search for short queries', () => {
    createComponent(mockColumn);

    component.onValueInput('h');
    jasmine.clock().tick(351);

    httpMock.expectNone(req => req.url.includes('/ontology/search/suggest/'));
  });

  it('should update edit value on input', () => {
    createComponent(mockColumn);

    component.onValueInput('test input');

    expect(component.editValue()).toBe('test input');
  });
});
