import { ComponentFixture, TestBed } from '@angular/core/testing';
import { provideZonelessChangeDetection } from '@angular/core';
import { ColumnInfo } from './column-info';
import { SdrfSyntaxService, MetadataColumn, OntologyType } from '@noatgnu/cupcake-vanilla';

function createMockColumn(overrides: Partial<MetadataColumn> = {}): MetadataColumn {
  return {
    id: 1,
    metadataTable: 1,
    name: 'characteristics[organism]',
    type: 'characteristics',
    columnPosition: 0,
    value: '',
    notApplicable: false,
    notAvailable: false,
    mandatory: false,
    hidden: false,
    autoGenerated: false,
    readonly: false,
    modifiers: [],
    suggestedValues: [],
    enableTypeahead: true,
    possibleDefaultValues: [],
    staffOnly: false,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    ...overrides
  };
}

describe('ColumnInfo', () => {
  let component: ColumnInfo;
  let fixture: ComponentFixture<ColumnInfo>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [ColumnInfo],
      providers: [
        provideZonelessChangeDetection(),
        SdrfSyntaxService
      ]
    }).compileComponents();

    fixture = TestBed.createComponent(ColumnInfo);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });

  it('should return null syntaxType when no column set', () => {
    expect(component.syntaxType()).toBeNull();
  });

  it('should return null parsedValue when no column set', () => {
    expect(component.parsedValue()).toBeNull();
  });

  it('should detect modification syntax type', () => {
    fixture.componentRef.setInput('column', createMockColumn({
      name: 'comment[modification parameters]',
      type: 'comment'
    }));
    expect(component.syntaxType()).toBe('modification');
    expect(component.syntaxLabel()).toBe('Modification Parameters');
  });

  it('should detect age syntax type', () => {
    fixture.componentRef.setInput('column', createMockColumn({
      name: 'characteristics[age]'
    }));
    expect(component.syntaxType()).toBe('age');
    expect(component.syntaxLabel()).toBe('Age Format');
  });

  it('should detect cleavage syntax type', () => {
    fixture.componentRef.setInput('column', createMockColumn({
      name: 'comment[cleavage agent details]',
      type: 'comment'
    }));
    expect(component.syntaxType()).toBe('cleavage');
    expect(component.syntaxLabel()).toBe('Cleavage Agent Details');
  });

  it('should parse modification cell value', () => {
    fixture.componentRef.setInput('column', createMockColumn({
      name: 'comment[modification parameters]',
      type: 'comment'
    }));
    fixture.componentRef.setInput('cellValue', 'NT=Carbamidomethyl;AC=UNIMOD:4;TA=C');

    const parsed = component.parsedValue();
    expect(parsed).toBeTruthy();
    expect(parsed!['NT']).toBe('Carbamidomethyl');
    expect(parsed!['AC']).toBe('UNIMOD:4');
    expect(parsed!['TA']).toBe('C');
  });

  it('should return null parsedValue for non-special column', () => {
    fixture.componentRef.setInput('column', createMockColumn());
    fixture.componentRef.setInput('cellValue', 'Homo sapiens');
    expect(component.parsedValue()).toBeNull();
  });

  it('should return null parsedValue when cell value is empty', () => {
    fixture.componentRef.setInput('column', createMockColumn({
      name: 'comment[modification parameters]',
      type: 'comment'
    }));
    fixture.componentRef.setInput('cellValue', '');
    expect(component.parsedValue()).toBeNull();
  });

  it('should return ontology label for ontology column', () => {
    fixture.componentRef.setInput('column', createMockColumn({
      ontologyType: OntologyType.SPECIES
    }));
    expect(component.ontologyLabel()).toBeTruthy();
  });

  it('should return correct column type label', () => {
    fixture.componentRef.setInput('column', createMockColumn({ type: 'characteristics' }));
    expect(component.columnTypeLabel()).toBe('Characteristics');

    fixture.componentRef.setInput('column', createMockColumn({ type: 'comment' }));
    expect(component.columnTypeLabel()).toBe('Comment');

    fixture.componentRef.setInput('column', createMockColumn({ type: 'factor value' }));
    expect(component.columnTypeLabel()).toBe('Factor Value');
  });

  it('should return object entries', () => {
    const entries = component.objectEntries({ NT: 'Carbamidomethyl', TA: 'C' });
    expect(entries).toContain(['NT', 'Carbamidomethyl'] as any);
    expect(entries).toContain(['TA', 'C'] as any);
  });
});
