import { ComponentFixture, TestBed } from '@angular/core/testing';
import { FormsModule } from '@angular/forms';
import { BasicAutofillComponent } from './basic-autofill';

describe('BasicAutofillComponent', () => {
  let component: BasicAutofillComponent;
  let fixture: ComponentFixture<BasicAutofillComponent>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [BasicAutofillComponent, FormsModule]
    }).compileComponents();

    fixture = TestBed.createComponent(BasicAutofillComponent);
    component = fixture.componentInstance;
    component.column = {
      id: 1,
      metadataTable: 1,
      columnName: 'test column',
      displayName: 'Test Column',
      columnType: 'text',
      columnPosition: 0,
      mandatory: false,
      hidden: false,
      readonly: false,
      value: '',
      modifiers: [],
      enableTypeahead: false,
      notApplicable: false,
      notAvailable: false,
      autoGenerated: false,
      suggestedValues: [],
      validationRules: {},
      metadataColumnPool: null,
      baseColumn: false,
      createdAt: '2023-01-01T00:00:00Z',
      updatedAt: '2023-01-01T00:00:00Z'
    };
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
