import { ComponentFixture, TestBed, fakeAsync, tick } from '@angular/core/testing';
import { provideHttpClient } from '@angular/common/http';
import { provideHttpClientTesting, HttpTestingController } from '@angular/common/http/testing';
import { ColumnList } from './column-list';
import { ExcelService } from '../../core/services/excel.service';
import { ToastService } from '../../core/services/toast.service';
import {
  MetadataTableService,
  MetadataColumnService,
  SdrfSyntaxService,
  MetadataTable,
  MetadataColumn,
  OntologyType
} from '@noatgnu/cupcake-vanilla';

function createMockColumn(overrides: Partial<MetadataColumn> = {}): MetadataColumn {
  return {
    id: 1,
    metadataTable: 1,
    name: 'test column',
    type: 'characteristics',
    columnPosition: 0,
    value: '',
    notApplicable: false,
    notAvailable: false,
    mandatory: false,
    hidden: false,
    autoGenerated: false,
    readonly: false,
    modifiers: [],
    suggestedValues: [],
    enableTypeahead: true,
    possibleDefaultValues: [],
    staffOnly: false,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    ...overrides
  };
}

function createMockTable(overrides: Partial<MetadataTable> = {}): MetadataTable {
  return {
    id: 1,
    name: 'Test Table',
    sampleCount: 10,
    version: '1.0',
    isLocked: false,
    isPublished: false,
    visibility: 'private',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    ...overrides
  };
}

describe('ColumnList', () => {
  let component: ColumnList;
  let fixture: ComponentFixture<ColumnList>;
  let httpMock: HttpTestingController;
  let excelServiceSpy: jasmine.SpyObj<ExcelService>;
  let toastServiceSpy: jasmine.SpyObj<ToastService>;

  const mockColumns: MetadataColumn[] = [
    createMockColumn({
      id: 1,
      name: 'source name',
      type: 'source_name',
      mandatory: true,
      columnPosition: 0
    }),
    createMockColumn({
      id: 2,
      name: 'characteristics[organism]',
      type: 'characteristics',
      columnPosition: 1,
      ontologyType: OntologyType.SPECIES
    }),
    createMockColumn({
      id: 3,
      name: 'characteristics[age]',
      type: 'characteristics',
      columnPosition: 2
    })
  ];

  const mockTable = createMockTable({
    columns: mockColumns
  });

  beforeEach(async () => {
    excelServiceSpy = jasmine.createSpyObj('ExcelService', ['getSelectedRange']);
    toastServiceSpy = jasmine.createSpyObj('ToastService', ['success', 'error', 'warning', 'info']);

    excelServiceSpy.getSelectedRange.and.returnValue(Promise.resolve({
      address: 'Sheet1!A2',
      values: [['test value']]
    }));

    await TestBed.configureTestingModule({
      imports: [ColumnList],
      providers: [
        provideHttpClient(),
        provideHttpClientTesting(),
        MetadataTableService,
        MetadataColumnService,
        SdrfSyntaxService,
        { provide: ExcelService, useValue: excelServiceSpy },
        { provide: ToastService, useValue: toastServiceSpy }
      ]
    }).compileComponents();

    httpMock = TestBed.inject(HttpTestingController);
    fixture = TestBed.createComponent(ColumnList);
    component = fixture.componentInstance;
    fixture.componentRef.setInput('table', mockTable);
    fixture.detectChanges();
  });

  afterEach(() => {
    httpMock.verify();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });

  it('should initialize with columns from table', () => {
    expect(component.columns().length).toBe(3);
  });

  it('should sort columns by position', () => {
    const columns = component.columns();
    expect(columns[0].columnPosition).toBe(0);
    expect(columns[1].columnPosition).toBe(1);
    expect(columns[2].columnPosition).toBe(2);
  });

  it('should filter columns by search query', () => {
    component.searchQuery.set('organism');
    const filtered = component.filteredColumns();
    expect(filtered.length).toBe(1);
    expect(filtered[0].name).toContain('organism');
  });

  it('should return all columns when search is empty', () => {
    component.searchQuery.set('');
    const filtered = component.filteredColumns();
    expect(filtered.length).toBe(3);
  });

  it('should detect columns with special input', () => {
    const ageColumn = mockColumns.find(c => c.name.includes('age'))!;
    expect(component.hasSpecialInput(ageColumn)).toBeTrue();

    const organismColumn = mockColumns.find(c => c.name.includes('organism'))!;
    expect(component.hasSpecialInput(organismColumn)).toBeTrue();
  });

  it('should open column editor for editing', () => {
    const column = mockColumns[0];
    component.editColumn(column);

    expect(component.selectedColumn()).toBe(column);
    expect(component.isCreating()).toBeFalse();
    expect(component.viewMode()).toBe('column-editor');
  });

  it('should open column editor for creating', () => {
    component.createColumn();

    expect(component.selectedColumn()).toBeNull();
    expect(component.isCreating()).toBeTrue();
    expect(component.viewMode()).toBe('column-editor');
  });

  it('should open value helper for column', fakeAsync(() => {
    const column = mockColumns[1];
    component.openValueHelper(column);
    tick();

    expect(component.selectedColumn()).toBe(column);
    expect(component.viewMode()).toBe('cell-editor');
  }));

  it('should close column editor on save', () => {
    component.viewMode.set('column-editor');
    component.selectedColumn.set(mockColumns[0]);

    component.onColumnSaved();

    expect(component.viewMode()).toBe('list');
    expect(component.selectedColumn()).toBeNull();
  });

  it('should close column editor on cancel', () => {
    component.viewMode.set('column-editor');
    component.selectedColumn.set(mockColumns[0]);

    component.onEditorCancel();

    expect(component.viewMode()).toBe('list');
    expect(component.selectedColumn()).toBeNull();
  });

  it('should close cell editor', () => {
    component.viewMode.set('cell-editor');
    component.selectedColumn.set(mockColumns[0]);

    component.onCellEditorClose();

    expect(component.viewMode()).toBe('list');
    expect(component.selectedColumn()).toBeNull();
  });

  it('should emit back event', () => {
    const backSpy = spyOn(component.back, 'emit');

    component.goBack();

    expect(backSpy).toHaveBeenCalled();
  });

  it('should warn when deleting mandatory column', () => {
    const mandatoryColumn = mockColumns[0];
    component.deleteColumn(mandatoryColumn);

    expect(toastServiceSpy.warning).toHaveBeenCalledWith('Cannot delete mandatory column');
  });

  it('should delete non-mandatory column', fakeAsync(() => {
    const column = mockColumns[1];
    const refreshSpy = spyOn(component.refresh, 'emit');

    component.deleteColumn(column);

    const req = httpMock.expectOne(req => req.url.includes(`/metadata-tables/${mockTable.id}/remove-column/`));
    req.flush({});
    tick();

    expect(toastServiceSpy.success).toHaveBeenCalled();
    expect(refreshSpy).toHaveBeenCalled();
  }));

  it('should handle delete error', fakeAsync(() => {
    const column = mockColumns[1];

    component.deleteColumn(column);

    const req = httpMock.expectOne(req => req.url.includes(`/metadata-tables/${mockTable.id}/remove-column/`));
    req.error(new ErrorEvent('Network error'));
    tick();

    expect(toastServiceSpy.error).toHaveBeenCalledWith('Failed to delete column');
  }));

  it('should get current cell value when opening value helper', fakeAsync(() => {
    excelServiceSpy.getSelectedRange.and.returnValue(Promise.resolve({
      address: 'Sheet1!B2',
      values: [['existing value']]
    }));

    component.openValueHelper(mockColumns[1]);
    tick();

    expect(component.currentCellValue()).toBe('existing value');
  }));

  it('should handle Excel error when opening value helper', fakeAsync(() => {
    excelServiceSpy.getSelectedRange.and.returnValue(Promise.reject('Excel error'));

    component.openValueHelper(mockColumns[1]);
    tick();

    expect(component.currentCellValue()).toBe('');
    expect(component.viewMode()).toBe('cell-editor');
  }));
});
