version: '3.8'

services:
  cupcake-builder:
    build:
      context: ..  # Build context is parent directory
      dockerfile: docker-build/Dockerfile.build
    environment:
      - BUILD_TARGET=${BUILD_TARGET:-linux}
      - BACKEND_REPO_URL=${BACKEND_REPO_URL}
      - BACKEND_BRANCH=${BACKEND_BRANCH:-main}
    volumes:
      - ../docker-dist:/app/dist-output
      - ../docker-cache/npm:/root/.npm
      - ../docker-cache/node_modules:/app/node_modules
      - ../docker-cache/electron-node_modules:/app/electron-app/node_modules
    working_dir: /app
    command: /app/docker-build.sh

  # Development service for testing the build process
  cupcake-dev:
    build:
      context: ..  # Build context is parent directory
      dockerfile: docker-build/Dockerfile.build
    environment:
      - BUILD_TARGET=linux
      - BACKEND_REPO_URL=${BACKEND_REPO_URL}
      - BACKEND_BRANCH=${BACKEND_BRANCH:-main}
    volumes:
      - ..:/app
      - ../docker-cache/npm:/root/.npm
    working_dir: /app
    ports:
      - "4200:4200"  # Angular dev server
      - "8000:8000"  # Django backend
    command: bash -c "npm install && cd electron-app && npm install && npm run dev"

networks:
  default:
    name: cupcake-build-network
