import { ComponentFixture, TestBed } from '@angular/core/testing';
import { provideZonelessChangeDetection } from '@angular/core';
import { provideHttpClient } from '@angular/common/http';
import { provideHttpClientTesting, HttpTestingController } from '@angular/common/http/testing';
import { FavoritesPanel } from './favorites-panel';
import { ExcelService } from '../../core/services/excel.service';
import { ToastService } from '../../core/services/toast.service';
import {
  FavouriteMetadataOptionService,
  MetadataColumn
} from '@noatgnu/cupcake-vanilla';
import { AuthService, LabGroupService, User, CUPCAKE_CORE_CONFIG } from '@noatgnu/cupcake-core';

function createMockUser(): User {
  return {
    id: 1,
    username: 'testuser',
    email: 'test@example.com',
    isStaff: false,
    isSuperuser: false,
    isActive: true,
    dateJoined: '2024-01-01T00:00:00Z',
    hasOrcid: false
  };
}

function createMockColumn(overrides: Partial<MetadataColumn> = {}): MetadataColumn {
  return {
    id: 1,
    metadataTable: 1,
    name: 'test column',
    type: 'characteristics',
    columnPosition: 0,
    value: '',
    notApplicable: false,
    notAvailable: false,
    mandatory: false,
    hidden: false,
    autoGenerated: false,
    readonly: false,
    modifiers: [],
    suggestedValues: [],
    enableTypeahead: true,
    possibleDefaultValues: [],
    staffOnly: false,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    ...overrides
  };
}

describe('FavoritesPanel', () => {
  let component: FavoritesPanel;
  let fixture: ComponentFixture<FavoritesPanel>;
  let httpMock: HttpTestingController;
  let excelServiceSpy: jasmine.SpyObj<ExcelService>;
  let toastServiceSpy: jasmine.SpyObj<ToastService>;
  let authServiceSpy: jasmine.SpyObj<AuthService>;

  const mockColumn = createMockColumn({
    name: 'characteristics[organism]'
  });

  beforeEach(async () => {
    excelServiceSpy = jasmine.createSpyObj('ExcelService', ['getSelectedRange', 'updateCell']);
    excelServiceSpy.getSelectedRange.and.returnValue(Promise.resolve({
      address: 'Sheet1!A2',
      values: [['test value']]
    }));
    excelServiceSpy.updateCell.and.returnValue(Promise.resolve());

    toastServiceSpy = jasmine.createSpyObj('ToastService', ['success', 'error']);
    authServiceSpy = jasmine.createSpyObj('AuthService', ['getCurrentUser']);
    authServiceSpy.getCurrentUser.and.returnValue(createMockUser());

    await TestBed.configureTestingModule({
      imports: [FavoritesPanel],
      providers: [
        provideZonelessChangeDetection(),
        provideHttpClient(),
        provideHttpClientTesting(),
        FavouriteMetadataOptionService,
        LabGroupService,
        { provide: CUPCAKE_CORE_CONFIG, useValue: { apiUrl: 'http://localhost:8000/api/v1' } },
        { provide: ExcelService, useValue: excelServiceSpy },
        { provide: ToastService, useValue: toastServiceSpy },
        { provide: AuthService, useValue: authServiceSpy }
      ]
    }).compileComponents();

    httpMock = TestBed.inject(HttpTestingController);
    fixture = TestBed.createComponent(FavoritesPanel);
    component = fixture.componentInstance;

    fixture.detectChanges();
    const labGroupReq = httpMock.expectOne(req => req.url.includes('/lab-groups/mine/'));
    labGroupReq.flush({ count: 0, results: [] });
    await fixture.whenStable();
  });

  afterEach(() => {
    httpMock.verify();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });

  it('should initialize with empty favorites', () => {
    expect(component.userFavorites().length).toBe(0);
    expect(component.labGroupFavorites().length).toBe(0);
    expect(component.globalFavorites().length).toBe(0);
    expect(component.hasFavorites).toBeFalse();
  });

  it('should load favorites when column is provided', async () => {
    fixture.componentRef.setInput('column', mockColumn);
    fixture.detectChanges();
    await fixture.whenStable();

    const userReq = httpMock.expectOne(req =>
      req.url.includes('/favourite-options/') && req.params.get('userId') === '1'
    );
    userReq.flush({ count: 1, results: [{ id: 1, name: 'characteristics[organism]', value: 'Homo sapiens' }] });

    const globalReq = httpMock.expectOne(req =>
      req.url.includes('/favourite-options/') && req.params.get('isGlobal') === 'true'
    );
    globalReq.flush({ count: 0, results: [] });
    await fixture.whenStable();

    expect(component.userFavorites().length).toBe(1);
    expect(component.hasFavorites).toBeTrue();
  });

  it('should switch tabs', () => {
    component.setTab('labGroup');
    expect(component.activeTab()).toBe('labGroup');

    component.setTab('global');
    expect(component.activeTab()).toBe('global');

    component.setTab('user');
    expect(component.activeTab()).toBe('user');
  });

  it('should insert favorite into cell', async () => {
    const favorite = { id: 1, name: 'test', value: 'Test Value', isGlobal: false };
    component.insertFavorite(favorite as any);
    await fixture.whenStable();

    expect(excelServiceSpy.updateCell).toHaveBeenCalled();
    expect(toastServiceSpy.success).toHaveBeenCalledWith('Value inserted');
  });

  it('should show error on insert failure', async () => {
    excelServiceSpy.getSelectedRange.and.returnValue(Promise.reject('Excel error'));

    const favorite = { id: 1, name: 'test', value: 'Test Value', isGlobal: false };
    component.insertFavorite(favorite as any);
    await fixture.whenStable();

    expect(toastServiceSpy.error).toHaveBeenCalledWith('Failed to insert value');
  });

  it('should get display value from favorite', () => {
    const favoriteWithDisplay = { id: 1, name: 'test', value: 'actual', displayValue: 'Display', isGlobal: false };
    expect(component.getDisplayValue(favoriteWithDisplay as any)).toBe('Display');

    const favoriteWithoutDisplay = { id: 2, name: 'test', value: 'actual', isGlobal: false };
    expect(component.getDisplayValue(favoriteWithoutDisplay as any)).toBe('actual');
  });

  it('should clear favorites when column is removed', async () => {
    fixture.componentRef.setInput('column', mockColumn);
    fixture.detectChanges();
    await fixture.whenStable();

    const userReq = httpMock.expectOne(req =>
      req.url.includes('/favourite-options/') && req.params.get('userId') === '1'
    );
    userReq.flush({ count: 1, results: [{ id: 1, name: 'characteristics[organism]', value: 'Homo sapiens' }] });

    const globalReq = httpMock.expectOne(req =>
      req.url.includes('/favourite-options/') && req.params.get('isGlobal') === 'true'
    );
    globalReq.flush({ count: 0, results: [] });
    await fixture.whenStable();

    expect(component.userFavorites().length).toBe(1);

    fixture.componentRef.setInput('column', null);
    fixture.detectChanges();
    await fixture.whenStable();

    expect(component.userFavorites().length).toBe(0);
    expect(component.labGroupFavorites().length).toBe(0);
    expect(component.globalFavorites().length).toBe(0);
  });
});
