import { ComponentFixture, TestBed, fakeAsync, tick } from '@angular/core/testing';
import { provideHttpClient } from '@angular/common/http';
import { provideHttpClientTesting, HttpTestingController } from '@angular/common/http/testing';
import { OntologySearch } from './ontology-search';
import { ExcelService } from '../../core/services/excel.service';
import {
  OntologySearchService,
  OntologySuggestion,
  OntologyType,
  MetadataColumn
} from '@noatgnu/cupcake-vanilla';

function createMockColumn(overrides: Partial<MetadataColumn> = {}): MetadataColumn {
  return {
    id: 1,
    metadataTable: 1,
    name: 'test column',
    type: 'characteristics',
    columnPosition: 0,
    value: '',
    notApplicable: false,
    notAvailable: false,
    mandatory: false,
    hidden: false,
    autoGenerated: false,
    readonly: false,
    modifiers: [],
    suggestedValues: [],
    enableTypeahead: true,
    possibleDefaultValues: [],
    staffOnly: false,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    ...overrides
  };
}

describe('OntologySearch', () => {
  let component: OntologySearch;
  let fixture: ComponentFixture<OntologySearch>;
  let httpMock: HttpTestingController;
  let excelServiceSpy: jasmine.SpyObj<ExcelService>;

  const mockColumn = createMockColumn({
    name: 'characteristics[organism]',
    ontologyType: OntologyType.SPECIES
  });

  beforeEach(async () => {
    excelServiceSpy = jasmine.createSpyObj('ExcelService', ['getSelectedRange', 'updateCell']);
    excelServiceSpy.getSelectedRange.and.returnValue(Promise.resolve({
      address: 'Sheet1!A2',
      values: [['test value']]
    }));
    excelServiceSpy.updateCell.and.returnValue(Promise.resolve());

    await TestBed.configureTestingModule({
      imports: [OntologySearch],
      providers: [
        provideHttpClient(),
        provideHttpClientTesting(),
        OntologySearchService,
        { provide: ExcelService, useValue: excelServiceSpy }
      ]
    }).compileComponents();

    httpMock = TestBed.inject(HttpTestingController);
    fixture = TestBed.createComponent(OntologySearch);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  afterEach(() => {
    httpMock.verify();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });

  it('should initialize with default values', () => {
    expect(component.searchQuery()).toBe('');
    expect(component.selectedType()).toBe(OntologyType.NONE);
    expect(component.searchMatch()).toBe('contains');
    expect(component.suggestions().length).toBe(0);
    expect(component.showResults()).toBeFalse();
  });

  it('should have all ontology types available', () => {
    expect(component.ontologyTypes.length).toBeGreaterThan(0);
    expect(component.ontologyTypes.some(t => t.value === OntologyType.SPECIES)).toBeTrue();
    expect(component.ontologyTypes.some(t => t.value === OntologyType.TISSUE)).toBeTrue();
  });

  it('should search on input change', fakeAsync(() => {
    component.onSearchInput('human');
    tick(350);

    const req = httpMock.expectOne(req => req.url.includes('/ontology/search/suggest/'));
    expect(req.request.params.get('q')).toBe('human');
    req.flush({ suggestions: [] });
  }));

  it('should filter by selected type', fakeAsync(() => {
    component.selectedType.set(OntologyType.SPECIES);
    component.onSearchInput('human');
    tick(350);

    const req = httpMock.expectOne(req => req.url.includes('/ontology/search/suggest/'));
    expect(req.request.params.get('type')).toBe('species');
    req.flush({ suggestions: [] });
  }));

  it('should not search for short queries', fakeAsync(() => {
    component.onSearchInput('h');
    tick(350);

    httpMock.expectNone(req => req.url.includes('/ontology/search/suggest/'));
  }));

  it('should update type and re-search', fakeAsync(() => {
    component.searchQuery.set('human');
    component.onTypeChange(OntologyType.SPECIES);
    tick(350);

    const req = httpMock.expectOne(req => req.url.includes('/ontology/search/suggest/'));
    expect(req.request.params.get('type')).toBe('species');
    req.flush({ suggestions: [] });
  }));

  it('should change search match type', fakeAsync(() => {
    component.searchQuery.set('human');
    component.onMatchChange('startswith');
    tick(350);

    expect(component.searchMatch()).toBe('startswith');
    const req = httpMock.expectOne(req => req.url.includes('/ontology/search/suggest/'));
    expect(req.request.params.get('match')).toBe('startswith');
    req.flush({ suggestions: [] });
  }));

  it('should use contains match by default', fakeAsync(() => {
    component.onSearchInput('human');
    tick(350);

    const req = httpMock.expectOne(req => req.url.includes('/ontology/search/suggest/'));
    expect(req.request.params.get('match')).toBe('contains');
    req.flush({ suggestions: [] });
  }));

  it('should display suggestions', fakeAsync(() => {
    const mockSuggestions: OntologySuggestion[] = [
      {
        id: '9606',
        value: 'Homo sapiens',
        displayName: 'Homo sapiens',
        ontologyType: OntologyType.SPECIES
      }
    ];

    component.onSearchInput('human');
    tick(350);

    const req = httpMock.expectOne(req => req.url.includes('/ontology/search/suggest/'));
    req.flush({ suggestions: mockSuggestions });

    expect(component.suggestions().length).toBe(1);
    expect(component.showResults()).toBeTrue();
  }));

  it('should select suggestion and emit term with displayName only', fakeAsync(() => {
    const termSpy = spyOn(component.termSelected, 'emit');
    const suggestion: OntologySuggestion = {
      id: '9606',
      value: 'Homo sapiens',
      displayName: 'Homo sapiens',
      ontologyType: OntologyType.SPECIES
    };

    component.selectSuggestion(suggestion);
    tick();

    expect(termSpy).toHaveBeenCalledWith('Homo sapiens');
    expect(component.searchQuery()).toBe('');
    expect(component.showResults()).toBeFalse();
  }));

  it('should format MS_UNIQUE_VOCABULARIES with NT/AC syntax', fakeAsync(() => {
    const termSpy = spyOn(component.termSelected, 'emit');
    const suggestion: OntologySuggestion = {
      id: 'MS:1001251',
      value: 'Trypsin',
      displayName: 'Trypsin',
      ontologyType: OntologyType.MS_UNIQUE_VOCABULARIES,
      fullData: {
        name: 'Trypsin',
        accession: 'MS:1001251'
      }
    };

    component.selectSuggestion(suggestion);
    tick();

    expect(termSpy).toHaveBeenCalledWith('NT=Trypsin;AC=MS:1001251');
  }));

  it('should insert term into cell', fakeAsync(() => {
    const suggestion: OntologySuggestion = {
      id: '9606',
      value: 'Homo sapiens',
      displayName: 'Homo sapiens',
      ontologyType: OntologyType.SPECIES
    };

    component.insertIntoCell(suggestion);
    tick();

    expect(excelServiceSpy.updateCell).toHaveBeenCalled();
    expect(component.searchQuery()).toBe('');
    expect(component.showResults()).toBeFalse();
  }));

  it('should hide results after delay', fakeAsync(() => {
    component.showResults.set(true);
    component.hideResults();

    expect(component.showResults()).toBeTrue();
    tick(250);
    expect(component.showResults()).toBeFalse();
  }));

  it('should get ontology type label', () => {
    const label = component.getOntologyTypeLabel('species');
    expect(label).toBe('Species');
  });

  it('should set context when column is provided', fakeAsync(() => {
    fixture.componentRef.setInput('column', mockColumn);
    fixture.detectChanges();
    tick();

    expect(component.selectedType()).toBe(OntologyType.SPECIES);
    expect(component.contextLabel()).toBeTruthy();
  }));

  it('should filter by column ontology type when searching', fakeAsync(() => {
    fixture.componentRef.setInput('column', mockColumn);
    fixture.detectChanges();
    tick();

    component.onSearchInput('human');
    tick(350);

    const req = httpMock.expectOne(req => req.url.includes('/ontology/search/suggest/'));
    expect(req.request.params.get('type')).toBe('species');
    req.flush({ suggestions: [] });
  }));

  it('should handle search error gracefully', fakeAsync(() => {
    component.onSearchInput('human');
    tick(350);

    const req = httpMock.expectOne(req => req.url.includes('/ontology/search/suggest/'));
    req.error(new ErrorEvent('Network error'));

    expect(component.suggestions().length).toBe(0);
    expect(component.isSearching()).toBeFalse();
  }));

  it('should emit term on cell insert failure', fakeAsync(() => {
    const termSpy = spyOn(component.termSelected, 'emit');
    excelServiceSpy.getSelectedRange.and.returnValue(Promise.reject('Excel error'));

    const suggestion: OntologySuggestion = {
      id: '9606',
      value: 'Homo sapiens',
      displayName: 'Homo sapiens',
      ontologyType: OntologyType.SPECIES
    };

    component.insertIntoCell(suggestion);
    tick();

    expect(termSpy).toHaveBeenCalledWith('Homo sapiens');
  }));
});
