name: Build and Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  build-all-platforms:
    name: Build and Upload Release Assets
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build for All Platforms
        working-directory: ./docker-build
        run: |
          chmod +x build-docker.sh
          ./build-docker.sh all

      - name: Upload artifacts
        if: github.event_name == 'release'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: docker-dist/**/*
          retention-days: 7

      - name: Upload Release Assets
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            docker-dist/*.AppImage
            docker-dist/*.tar.gz
            docker-dist/*.exe
            docker-dist/*.zip
            docker-dist/*.dmg
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
