name: Build Cupcake Vanilla

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      backend_repo_url:
        description: 'Backend repository URL'
        required: true
        default: 'https://github.com/noatgnu/cupcake_vanilla.git'
      backend_branch:
        description: 'Backend branch to use'
        required: false
        default: 'master'

env:
  BACKEND_REPO_URL: ${{ github.event.inputs.backend_repo_url || secrets.BACKEND_REPO_URL }}
  BACKEND_BRANCH: ${{ github.event.inputs.backend_branch || 'master' }}

jobs:
  build-all-platforms:
    name: Build All Platforms
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build for All Platforms
        working-directory: ./docker-build
        run: |
          chmod +x build-docker.sh
          ./build-docker.sh all
