name: Build Cupcake Vanilla

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  build-all-platforms:
    name: Build All Platforms
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build for All Platforms
        working-directory: ./docker-build
        run: |
          chmod +x build-docker.sh
          ./build-docker.sh all
