name: Build Cupcake Vanilla

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

env:
  BACKEND_REPO_URL: ${{ secrets.BACKEND_REPO_URL || 'https://github.com/noatgnu/cupcake_vanilla.git' }}
  BACKEND_BRANCH: 'master'

jobs:
  build-all-platforms:
    name: Build All Platforms
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build for All Platforms
        working-directory: ./docker-build
        run: |
          chmod +x build-docker.sh
          ./build-docker.sh all
